version: "3.8"

services:
  api:
    container_name: bartugweb_api
    build: .
    environment:
      - ConnectionStrings__PostgreSqlDefault=Server=postgres;Port=5432;Database=bartugweb_db;User Id=bartugweb_user;Password=bartugweb_password_1048
      - ASPNETCORE_ENVIRONMENT=Development 
      - ASPNETCORE_URLS=http://+:8080
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - DefaultAdmin__Username=${DEFAULT_ADMIN_USER}
      - DefaultAdmin__Password=${DEFAULT_ADMIN_PASS}
      - Storage__Endpoint=${STORAGE_ENDPOINT}
      - Storage__AccessKeyId=${STORAGE_ACCESS_KEY_ID}
      - Storage__SecretAccessKey=${STORAGE_SECRET_ACCESS_KEY}
      - Storage__PublicBaseUrl=${STORAGE_PUBLIC_BASE_URL}
    networks:
      - bartugweb_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  
  postgres:
    image: postgres:16-alpine
    container_name: bartugweb_postgres
    environment:
      POSTGRES_DB: bartugweb_db
      POSTGRES_USER: bartugweb_user
      POSTGRES_PASSWORD: bartugweb_password_1048
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bartugweb_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bartugweb_user -d bartugweb_db"]
      interval: 10s
      timeout: 5s
      retries: 5


  nginx:
    image: nginx:1.25-alpine
    container_name: bartugweb_nginx
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ~/certbot/www:/var/www/certbot 
      - certbot-certs:/etc/letsencrypt 
    networks:
      - bartugweb_network
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  certbot-certs: 

networks:
  bartugweb_network:
    driver: bridge